/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LogsIndexRouteImport } from './routes/logs.index'
import { Route as BeansIndexRouteImport } from './routes/beans.index'
import { Route as AnalysisIndexRouteImport } from './routes/analysis.index'
import { Route as LogsNewRouteImport } from './routes/logs.new'
import { Route as BeansNewRouteImport } from './routes/beans.new'
import { Route as LogsLogIdIndexRouteImport } from './routes/logs.$logId.index'
import { Route as BeansBeanIdIndexRouteImport } from './routes/beans.$beanId.index'
import { Route as LogsLogIdEditRouteImport } from './routes/logs.$logId.edit'
import { Route as BeansBeanIdEditRouteImport } from './routes/beans.$beanId.edit'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIndexRoute = LogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeansIndexRoute = BeansIndexRouteImport.update({
  id: '/beans/',
  path: '/beans/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIndexRoute = AnalysisIndexRouteImport.update({
  id: '/analysis/',
  path: '/analysis/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsNewRoute = LogsNewRouteImport.update({
  id: '/logs/new',
  path: '/logs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BeansNewRoute = BeansNewRouteImport.update({
  id: '/beans/new',
  path: '/beans/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsLogIdIndexRoute = LogsLogIdIndexRouteImport.update({
  id: '/logs/$logId/',
  path: '/logs/$logId/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeansBeanIdIndexRoute = BeansBeanIdIndexRouteImport.update({
  id: '/beans/$beanId/',
  path: '/beans/$beanId/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsLogIdEditRoute = LogsLogIdEditRouteImport.update({
  id: '/logs/$logId/edit',
  path: '/logs/$logId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const BeansBeanIdEditRoute = BeansBeanIdEditRouteImport.update({
  id: '/beans/$beanId/edit',
  path: '/beans/$beanId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/beans/new': typeof BeansNewRoute
  '/logs/new': typeof LogsNewRoute
  '/analysis/': typeof AnalysisIndexRoute
  '/beans/': typeof BeansIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/beans/$beanId/edit': typeof BeansBeanIdEditRoute
  '/logs/$logId/edit': typeof LogsLogIdEditRoute
  '/beans/$beanId/': typeof BeansBeanIdIndexRoute
  '/logs/$logId/': typeof LogsLogIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/beans/new': typeof BeansNewRoute
  '/logs/new': typeof LogsNewRoute
  '/analysis': typeof AnalysisIndexRoute
  '/beans': typeof BeansIndexRoute
  '/logs': typeof LogsIndexRoute
  '/beans/$beanId/edit': typeof BeansBeanIdEditRoute
  '/logs/$logId/edit': typeof LogsLogIdEditRoute
  '/beans/$beanId': typeof BeansBeanIdIndexRoute
  '/logs/$logId': typeof LogsLogIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/beans/new': typeof BeansNewRoute
  '/logs/new': typeof LogsNewRoute
  '/analysis/': typeof AnalysisIndexRoute
  '/beans/': typeof BeansIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/beans/$beanId/edit': typeof BeansBeanIdEditRoute
  '/logs/$logId/edit': typeof LogsLogIdEditRoute
  '/beans/$beanId/': typeof BeansBeanIdIndexRoute
  '/logs/$logId/': typeof LogsLogIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/beans/new'
    | '/logs/new'
    | '/analysis/'
    | '/beans/'
    | '/logs/'
    | '/beans/$beanId/edit'
    | '/logs/$logId/edit'
    | '/beans/$beanId/'
    | '/logs/$logId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/beans/new'
    | '/logs/new'
    | '/analysis'
    | '/beans'
    | '/logs'
    | '/beans/$beanId/edit'
    | '/logs/$logId/edit'
    | '/beans/$beanId'
    | '/logs/$logId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/beans/new'
    | '/logs/new'
    | '/analysis/'
    | '/beans/'
    | '/logs/'
    | '/beans/$beanId/edit'
    | '/logs/$logId/edit'
    | '/beans/$beanId/'
    | '/logs/$logId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  BeansNewRoute: typeof BeansNewRoute
  LogsNewRoute: typeof LogsNewRoute
  AnalysisIndexRoute: typeof AnalysisIndexRoute
  BeansIndexRoute: typeof BeansIndexRoute
  LogsIndexRoute: typeof LogsIndexRoute
  BeansBeanIdEditRoute: typeof BeansBeanIdEditRoute
  LogsLogIdEditRoute: typeof LogsLogIdEditRoute
  BeansBeanIdIndexRoute: typeof BeansBeanIdIndexRoute
  LogsLogIdIndexRoute: typeof LogsLogIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/': {
      id: '/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof LogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beans/': {
      id: '/beans/'
      path: '/beans'
      fullPath: '/beans/'
      preLoaderRoute: typeof BeansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/': {
      id: '/analysis/'
      path: '/analysis'
      fullPath: '/analysis/'
      preLoaderRoute: typeof AnalysisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/new': {
      id: '/logs/new'
      path: '/logs/new'
      fullPath: '/logs/new'
      preLoaderRoute: typeof LogsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beans/new': {
      id: '/beans/new'
      path: '/beans/new'
      fullPath: '/beans/new'
      preLoaderRoute: typeof BeansNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/$logId/': {
      id: '/logs/$logId/'
      path: '/logs/$logId'
      fullPath: '/logs/$logId/'
      preLoaderRoute: typeof LogsLogIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beans/$beanId/': {
      id: '/beans/$beanId/'
      path: '/beans/$beanId'
      fullPath: '/beans/$beanId/'
      preLoaderRoute: typeof BeansBeanIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/$logId/edit': {
      id: '/logs/$logId/edit'
      path: '/logs/$logId/edit'
      fullPath: '/logs/$logId/edit'
      preLoaderRoute: typeof LogsLogIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beans/$beanId/edit': {
      id: '/beans/$beanId/edit'
      path: '/beans/$beanId/edit'
      fullPath: '/beans/$beanId/edit'
      preLoaderRoute: typeof BeansBeanIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  BeansNewRoute: BeansNewRoute,
  LogsNewRoute: LogsNewRoute,
  AnalysisIndexRoute: AnalysisIndexRoute,
  BeansIndexRoute: BeansIndexRoute,
  LogsIndexRoute: LogsIndexRoute,
  BeansBeanIdEditRoute: BeansBeanIdEditRoute,
  LogsLogIdEditRoute: LogsLogIdEditRoute,
  BeansBeanIdIndexRoute: BeansBeanIdIndexRoute,
  LogsLogIdIndexRoute: LogsLogIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
